### ISSUE TITLE
Can't import larcv in python [LINUX]

### ISSUE THREAD

**Issue by coreyjadams** [DeepLearnPhysics/larcv3#1]
You may see something like this on linux:
```
$ python
Python 3.6.8 |Intel Corporation| (default, Mar  1 2019, 00:10:45)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import larcv
Traceback (most recent call last):
  File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/larcv.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: liblarcv3.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/__init__.py", line 2, in <module>
    from . import larcv
  File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/larcv.py", line 17, in <module>
    _larcv = swig_import_helper()
  File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/larcv.py", line 16, in swig_import_helper
    return importlib.import_module('_larcv')
  File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_larcv'
>>>
(dlp-viewer)
cadams@cc001 : tests
$ export LD_LIBRARY_PATH=/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/lib:$LD_LIBRARY_PATH
(dlp-viewer)
cadams@cc001 : tests
$ python
Python 3.6.8 |Intel Corporation| (default, Mar  1 2019, 00:10:45)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distribution
>>> import larcv
>>> larcv.larcv
<module 'larcv.larcv' from '/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/larcv.py'>
>>>
```

The key error here is "ImportError: liblarcv3.so: cannot open shared object file: No such file or directory".  The way larcv libraries are structured is that all of the C++ functions, classes, etc are in lib/liblarcv3.so (liblarcv3.dylib on mac) and all of the python wrapper code is in _larcv.so.  This keeps the interface python agnostic if you just want the C++ side of things.

On mac, the linking stage for _larcv.so (which is loaded by python when you import larcv) puts a relative path for liblarcv3 as lib/liblarcv3.dylib.  This seems to be broken on linux, and therefore it can't be found.  As a workaround, just set your LD_LIBRARY_PATH temporarily to include this path and it should work.  Note the line in the error:
`File "/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/larcv.py", line 16, in swig_import_helper`

This is giving you the full path to your installation.  Add the full path to LD_LIBRARY_PATH but replacing `larcv.py` at the end with `lib/` and you will be good to go:
`export LD_LIBRARY_PATH=/home/cadams/Cooley/DLP3/miniconda3/envs/dlp-viewer/lib/python3.6/site-packages/larcv-3.0a1-py3.6-linux-x86_64.egg/larcv/lib:$LD_LIBRARY_PATH`

**Comment by coreyjadams** [comment]
Ok I believe this is fixed.  I've checked on Centos but haven't verified this fix on ubuntu yet.

**Comment by coreyjadams** [comment]
The unit tests are passing in Travis CI which is Ubuntu, so I claim this is fixed and I'm closing this issue.
